spark.executor.extraJavaOptions  -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16m -XX:MaxGCPauseMillis=200
spark.driver.extraJavaOptions    -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=35
